### ISSUE TITLE
Baseline record: two ci=false cells fail on main, and local dbt reds are NO_RESULT not failures

### ISSUE THREAD

**Issue by rrnewton** [rrnewton/hermit#2103]
## Summary

Two `ci = false` cells fail on `main` today. Neither blocks CI (they are not in the required plan), but both were mistaken for regressions during PR-drain work, so recording them here so nobody attributes them to a batch. A third observation is an **environment** limitation, not a failure, and is the one most likely to be misread.

## 1. `backend-parity-c/rlimit-identity` verify/**dbt** — NOT a product failure

```
./ci/test_harness.sh run --test backend-parity-c/rlimit-identity --mode verify --include-manual
PASS  portable  verify  ptrace  backend-parity-c/rlimit-identity
FAIL  portable  verify  dbt     backend-parity-c/rlimit-identity - verify exited with status 1
PASS  portable  verify  kvm     backend-parity-c/rlimit-identity
```

**Cause: the local hermit build has no DBT support.** Proven with a trivial control rather than inferred from the fixture:

```
hermit --backend=dbt    -- /bin/true
  Error: backend `dbt` is unavailable: DBT support was not included in this build
hermit --backend=ptrace -- /bin/true      # rc 0
```

So **every** dbt cell fails identically on a devbox built without `third-party-backends`. This is `NO_RESULT`, not evidence of divergence. `main`'s required plan contains 8 dbt cells, so DBT is genuinely exercised in CI; it simply cannot be exercised on a default local build.

**Correction to an earlier report:** #2098's description records this cell as "FAIL — pre-existing". The observation is accurate (main's own fixture fails identically here) but the characterization is not: it is an unavailable backend, not a failing test. Corrected in a comment on that PR.

**Practical guidance:** treat a local dbt/sabre/liteinst red as NO_RESULT until you have confirmed the backend is compiled in. Probe with `hermit --backend=<b> -- /bin/true` first.

## 2. `shared-futex-c/qemu-net-init` verify/ptrace — a genuine pre-existing failure

```
FAIL  portable  verify  ptrace  shared-futex-c/qemu-net-init - verify exited with status 1
```

Confirmed pre-existing by restoring `origin/main`'s own copy of `tests/shared-futex-verify/qemu_net_init.c` over a feature branch and re-running: identical failure. Not caused by PR #1900 or any other in-flight change.

Root cause is structural and tracked separately in #2102: the fixture is written to run as PID 1 under a guest kernel but is registered against a driver that runs it as an ordinary Hermit guest.

## 3. Three `*_identity` fixtures do not compile on main

`tests/c/getpriority_identity.c`, `tests/c/sched_getaffinity_identity.c` and `tests/c/getcpu_identity.c` all fail the harness build:

```
error: implicit declaration of function 'syscall' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
```

They are `ci = false`, so main stays green. The fix is a `[test.build] cflags = ["-D_GNU_SOURCE"]` section on each manifest entry; verified locally that with it, ptrace and kvm both pass. PRs #1737, #1756 and #1734 each try to promote one of these to `ci = true` **without** fixing the build, so each would red main as written — flagged on those PRs.

This is the same class as the repair already applied to `backend-parity-c/mmap-layout-pointer-order` (#2098) and `backend-parity-c/host-identity` (#2100). It is a recurring pattern: a C fixture using GNU/POSIX interfaces registered with no `[test.build]`, inheriting strict `-std=c11`.

## Provenance

All observed during test-corpus PR-drain batches 1 and 2 (#2098, #2100). Hermit `51ef8072e4529c43cedda36b42c3105b4ca72024`, Reverie pin `99437f05`, host devbig030.

[impl agent, OPUS] [hermit-drain-corpus, devbig030]
